#!/bin/bash
set -e

function print_usage() {
	printf "Usage: $0 <path-to-entry>\n
Show the password for a given keepass path.\n
This command expects the keepass database to be available at /work/keepass.kdbx.\n
This command either expects an environment variable called KEEPASS_PASSWORD to be set
or that the keepass master password is passed via stdin.\n" >&2
	printf "$0 '/Root/a group/bar'\n" >&2
	exit 2
}

if [[ $# -ne 1 ]] ; then
    print_usage
fi

KEEPASS_ENTRY=$1
KEEPASS_FILE=/work/keepass.kdbx

if [ -z "$KEEPASS_PASSWORD" ]; then
  cat - | kpcli --readonly --kdb ${KEEPASS_FILE} --command "show -f '$KEEPASS_ENTRY'" | grep 'Pass' | sed 's/ Pass: //'
else
  echo "$KEEPASS_PASSWORD" | kpcli --readonly --kdb ${KEEPASS_FILE} --command "show -f '$KEEPASS_ENTRY'" | grep 'Pass' | sed 's/ Pass: //'
fi

